CREATE TABLE IF NOT EXISTS MAJOR (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    passwd VARCHAR(255) NOT NULL,
    balance DECIMAL(15,2) DEFAULT 100.00,
    failed_attempts INT DEFAULT 0,
    account_locked_until DATETIME DEFAULT NULL
) ENGINE=InnoDB;


